# Generated by Django 3.1.2 on 2020-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
