# Generated by Django 3.1.2 on 2020-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_registration_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
