# Generated by Django 3.1.2 on 2020-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_registration_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status_intro_class',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
